const WIDGET_1_DASHBOARD_1_DATA_ITEM = "cwhEsbBe6Zs";

const WIDGET_2_DASHBOARD_1_DATA_ITEM = "cPcvesqWRtH";

const WIDGET_3_DASHBOARD_1_DATA_ITEM = "dJhWRKs0fcq";

const WIDGET_4_DASHBOARD_1_DATA_ITEMS = [
  "cwhEsbBe6Zs",
  "cPcvesqWRtH",
  "dJhWRKs0fcq",
];

const WIDGET_5_DASHBOARD_1_DATA_ITEM = "dJhWRKs0fcq";

const WIDGET_6_DASHBOARD_1_DATA_ITEMS = [
  "j6KMK39OsGk",
  "LQDrtIwibHf",
  "yU7jURi1DCf",
];

const WIDGET_7_DASHBOARD_1_DATA_ITEMS = [
  "sISjKc2LEDg",
  "FSLrz90vXKf",
  "cPcvesqWRtH",
  "kyVKK0JcRPJ",
  "cwhEsbBe6Zs",
  "dJhWRKs0fcq",
];

export {
  WIDGET_1_DASHBOARD_1_DATA_ITEM,
  WIDGET_2_DASHBOARD_1_DATA_ITEM,
  WIDGET_3_DASHBOARD_1_DATA_ITEM,
  WIDGET_4_DASHBOARD_1_DATA_ITEMS,
  WIDGET_5_DASHBOARD_1_DATA_ITEM,
  WIDGET_6_DASHBOARD_1_DATA_ITEMS,
  WIDGET_7_DASHBOARD_1_DATA_ITEMS,
};
