const UP_TREND_COLOR = "#E61B1B";
const DOWN_TREND_COLOR = "#118861";

const WIDGET_6_DASHBOARD_5_COLORS = [];
const WIDGET_7_DASHBOARD_5_COLORS = [];
const WIDGET_8_DASHBOARD_5_COLORS = [];
const WIDGET_9_DASHBOARD_5_COLORS = [];
const WIDGET_10_DASHBOARD_5_COLORS = [];
const WIDGET_11_DASHBOARD_5_COLORS = [];
const WIDGET_12_DASHBOARD_5_COLORS = [];
const WIDGET_13_DASHBOARD_5_COLORS = [];
const WIDGET_14_DASHBOARD_5_COLORS = [];
const WIDGET_15_DASHBOARD_5_COLORS = [];
const WIDGET_16_DASHBOARD_5_COLORS = [];
const WIDGET_17_DASHBOARD_5_COLORS = [];

export {
  UP_TREND_COLOR,
  DOWN_TREND_COLOR,
  WIDGET_6_DASHBOARD_5_COLORS,
  WIDGET_7_DASHBOARD_5_COLORS,
  WIDGET_8_DASHBOARD_5_COLORS,
  WIDGET_9_DASHBOARD_5_COLORS,
  WIDGET_10_DASHBOARD_5_COLORS,
  WIDGET_11_DASHBOARD_5_COLORS,
  WIDGET_12_DASHBOARD_5_COLORS,
  WIDGET_13_DASHBOARD_5_COLORS,
  WIDGET_14_DASHBOARD_5_COLORS,
  WIDGET_15_DASHBOARD_5_COLORS,
  WIDGET_16_DASHBOARD_5_COLORS,
  WIDGET_17_DASHBOARD_5_COLORS,
};
